#! /bin/bash

LCFG_IMAGE_NAME="reverseproxy_nginx"
LCFG_IMAGE_VER="latest"

LCFG_NGINX_USER_ID=$(id -u ${USER})
#LCFG_NGINX_GROUP_ID=$(id -g ${USER})
LCFG_NGINX_GROUP_ID=$LCFG_NGINX_USER_ID

LCFG_CSR_SUBJECT_COUNTRY="DE"
LCFG_CSR_SUBJECT_STATE="SAX"
LCFG_CSR_SUBJECT_LOCATION="Leipzig"
LCFG_CSR_SUBJECT_ORGANIZ="TSANDK"
LCFG_CSR_SUBJECT_ORGUNIT="IT"
LCFG_CSR_SUBJECT_COMMONNAME="default.localhost"

docker build \
	--build-arg WWWDATA_USER_ID=$LCFG_NGINX_USER_ID \
	--build-arg WWWDATA_GROUP_ID=$LCFG_NGINX_GROUP_ID \
	--build-arg CSR_SUBJECT_COUNTRY="$LCFG_CSR_SUBJECT_COUNTRY" \
	--build-arg CSR_SUBJECT_STATE="$LCFG_CSR_SUBJECT_STATE" \
	--build-arg CSR_SUBJECT_LOCATION="$LCFG_CSR_SUBJECT_LOCATION" \
	--build-arg CSR_SUBJECT_ORGANIZ="$LCFG_CSR_SUBJECT_ORGANIZ" \
	--build-arg CSR_SUBJECT_ORGUNIT="$LCFG_CSR_SUBJECT_ORGUNIT" \
	--build-arg CSR_SUBJECT_COMMONNAME="$LCFG_CSR_SUBJECT_COMMONNAME" \
	-t "$LCFG_IMAGE_NAME":"$LCFG_IMAGE_VER" \
	-f Dockerfile \
	.
#[ $? -ne 0 ] && exit 1

#docker tag "$LCFG_IMAGE_NAME":"$LCFG_IMAGE_VER" "$LCFG_IMAGE_NAME":latest
